config/routes.rb
Brandscopic::Application.routes.draw do

  mount Nkss::Engine => '/styleguides' if Rails.env.development?
  apipie if ENV['WEB']

  # Redirect old urls to new ones
  get '/results/gva', to: redirect('/analysis/gva')
  get '/results/event_status', to: redirect('/analysis/event_status')
  get '/results/attendance', to: redirect('/analysis/attendance')

  concern :deactivatable do
    get :deactivate, on: :member
    get :activate, on: :member
  end

  concern :filterable do
    get :items, on: :collection, format: :html
  end

  concern :commentable do
    resources :comments, only: [:index, :create, :update, :destroy]
  end

  concern :api_attachable do
    get :form, on: :collection
  end

  concern :form_field_exportable do
    get :form, action: :export_fieldable, on: :member
    get :export_results, on: :member
  end

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create'
        delete 'sessions' => 'sessions#destroy'

        get '/companies' => 'users#companies'
        resources :users, only: [:index, :update, :show] do
          collection do
            match 'password/new_password', to: 'users#new_password', via: :post
            get :permissions
            get :notifications
          end
        end
        resources :activities, only: [:new, :show]

        resources :filters, only: [:show]

        resources :events, only: [:index, :show, :create, :update], concerns: [:commentable] do
          get :status_facets, on: :collection
          get :requiring_attention, on: :collection
          post :filter, to: 'events#index', on: :collection
          resources :photos, only: [:index, :create, :update], concerns: [:api_attachable]
          resources :documents, only: [:index, :create, :update], concerns: [:api_attachable]
          resources :event_expenses, only: [:index, :create, :destroy, :update], concerns: [:api_attachable]
          resources :tasks, only: [:index, :create]
          resources :surveys,  only: [:index, :create, :update, :show] do
            get :brands, on: :collection
          end
          resources :invites, only: [:index, :show, :create, :update]
          resources :activities, only: [:index, :create, :update], concerns: [:deactivatable, :api_attachable] do
            get :deactivate, on: :member
          end
          get :autocomplete,   on: :collection
          member do
            put :submit
            put :reject
            put :approve
            get :results
            get :members
            post :members, to: 'events#add_member'
            delete :members, to: 'events#delete_member'
            get :assignable_members
            get :contacts
            post :contacts, to: 'events#add_contact'
            delete :contacts, to: 'events#delete_contact'
            get :assignable_contacts
            get :details_counters
          end
        end

        resources :campaigns, only: [] do
          collection do
            get :all
            get :overall_stats
          end
          resources :activity_types, only: [:index]
          resources :brands, only: [:index]
          get :stats, on: :member
          get :events, on: :member
          get :expense_categories, on: :member
        end

        resources :activity_types, only: [:index] do
          member do
            get :campaigns
          end
        end

        resources :venues, only: [:index, :show, :create] do
          get :search, on: :collection
          get :types, on: :collection
          get :autocomplete, on: :collection
          resources :invites, only: [:index, :show, :create, :update]
          resources :activities, only: [:index, :create, :update] do
            get :deactivate, on: :member
          end
          member do
            get :analysis
            get :photos
            get :comments
          end
        end

        resources :areas, only: [:index] do
          get :cities, on: :member
        end

        resources :brands, only: [:index] do
          get :marques, on: :member
        end

        resources :countries, only: [:index] do
          get :states, on: :member
        end

        resources :contacts, only: [:index, :create, :update, :show]

        resources :tasks, only: [:update, :create, :show], concerns: [:commentable] do
          collection do
            get :mine, action: :index, defaults: { scope: 'user' }, constraints: { scope: 'user' }
            get :team, action: :index, defaults: { scope: 'teams' }, constraints: { scope: 'teams' }
          end
        end

        namespace :brand_ambassadors do
          resources :visits, only: [:index, :create, :update, :show] do
            get :types, on: :collection
            get :events, on: :member
          end
          resources :documents, only: [:create, :update, :destroy, :index]
        end
      end
    end
  end

  if ENV['WEB']
    require 'sidekiq/web'
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    authenticate :admin_user do
      mount Sidekiq::Web => '/_bgjobs' unless Rails.env.test?
    end
  end

  devise_for :users, controllers: { invitations: 'invitations', passwords: 'passwords' }

  devise_scope :user do
    put '/users/confirmation', to: 'confirmations#update'
    get '/users/invitation/resend', to: 'invitations#resend'
    get '/users/invitation/renew', to: 'invitations#renew'
    post '/users/invitation/resend', to: 'invitations#send_invite'
    get '/users/password/thanks', to: 'passwords#thanks', as: :passwords_thanks
  end

  put '/users/dismiss_alert', to: 'company_users#dismiss_alert'

  get 'select-company/:company_id', to: 'company_users#select_company', as: :select_company, constraints: { company_id: /[0-9]+/ }
  put 'login-as', to: 'company_users#select_custom_user', as: :select_custom_user

  resources :countries, only: [] do
    get :states, on: :collection
    get :cities, on: :member
  end

  get '/notifications.json', to: 'company_users#notifications', format: :json

  get 'exports/:download_id/status', to: 'company_users#export_status', as: :export_status, format: :json

  resources :goals, only: [:create, :update]

  resources :photos, only: [:show]

  # /filters/events /filters/campaigns etc
  resources :filters, only: [:show] do
    get :expand, on: :collection
  end

  # /autocomplete/events /autocomplete/campaigns etc
  resources :autocomplete, only: [:show]

  namespace :results do
    resources :event_data, only: [:index], concerns: [:filterable]
    resources :comments, only: [:index], concerns: [:filterable]
    resources :photos, only: [:index], concerns: [:filterable] do
      post 'downloads', to: 'photos#new_download', on: :collection, format: :js
      get 'downloads/:download_id', to: 'photos#download', on: :collection, as: :download, format: :js
      get 'downloads/:download_id/status', to: 'photos#download_status', on: :collection, as: :download_status, format: :json
    end
    resources :activities, only: [:index], concerns: [:filterable]
    resources :expenses, only: [:index], concerns: [:filterable]
    resources :surveys, only: [:index], concerns: [:filterable]

    # resources :attendance, only: [:index] do
    # end

    resources :reports, only: [:index, :new, :create, :edit, :update, :show],
                        concerns: [:deactivatable] do
      get :build, on: :member
      get :rows, on: :member
      get :filters, on: :member
      get :share, to: 'reports#share_form', on: :member
      post :preview, on: :member
    end

    resources :data_extracts, only: [:new, :create, :show, :edit, :update] do
      get :preview, on: :collection
      get :save, on: :collection
      get :available_fields, on: :collection
      get :items, on: :collection
      get :deactivate, on: :member
      get :activate, on: :member
    end

    # For The KPI report
    get :kpi_report, to: 'kpi_reports#index'

    post :kpi_report, to: 'kpi_reports#report'
    get :kpi_report_status, to: 'kpi_reports#status'

  end

  namespace :analysis do
    resources :trends, only: [] do
      collection do
        get :sources
        get :questions
        get :results
        get :items
        get :filters
        get :search
      end
      get 't/:term', on: :collection, action: :show
      get 't/:term/:action', on: :collection
    end

    get 'attendance/map', to: 'attendance#map', as: :attendance_map
    get 'attendance', to: 'attendance#index', as: :attendance

    get :gva, to: 'gva#index'
    post :gva, to: 'gva#report'
    get :report_groups, to: 'gva#report_groups'

    get :event_status, to: 'event_status#index'
    post :event_status, to: 'event_status#report'

    get :campaigns_report, to: 'campaigns_report#index'
    post :campaigns_report, to: 'campaigns_report#report'

    get :staff_report, to: 'staff_report#index'
    post :staff_report, to: 'staff_report#report'

    get :campaign_summary_report, to: 'campaign_summary_report#index'
    get :campaign_summary_report_show_all, to: 'campaign_summary_report#show_all'
    post :campaign_summary_report, to: 'campaign_summary_report#report'
    get :campaign_summary_report_export, to: 'campaign_summary_report#export_results'
    get :campaign_summary_report_items, to: 'campaign_summary_report#items'
    get :campaign_summary_report_result, to: 'campaign_summary_report#result'

    get '/', to: 'analysis#index'
  end

  scope '/research' do
    resources :venues, only: [:index, :show], concerns: [:filterable] do
      member do
        match 'areas/:area_id' => 'venues#delete_area', via: :delete, as: :delete_area
        match 'areas/select' => 'venues#select_areas', via: :get, as: :select_areas
        match 'areas/add' => 'venues#add_areas', via: :post, as: :add_area
        match 'areas' => 'venues#areas', via: :get, as: :areas
      end
      resources :events, only: [:new, :create]

app/controllers/results/activities_controller.rb
module Results
  class ActivitiesController < FilteredController
    defaults resource_class: ::Activity

    respond_to :xls, :pdf, only: :index
    helper_method :data_totals, :return_path

    private

    def collection_to_csv
      exporter = FormFieldDataExporter.new(current_company_user, search_params, resource_class)
      CSV.generate do |csv|
        csv << ['CAMPAIGN NAME', 'USER', 'DATE', 'ACTIVITY TYPE', 'AREAS', 'TD LINX CODE',
                'VENUE NAME', 'ADDRESS', 'CITY', 'STATE', 'ZIP', 'COUNTRY', 'ACTIVE STATE', 'CREATED AT',
                'CREATED BY', 'LAST MODIFIED', 'MODIFIED BY'] +
               exporter.custom_fields_to_export_headers
        each_collection_item do |activity|
          csv << [
            activity.campaign_name, activity.company_user_full_name, activity.date, activity.activity_type_name,
            exporter.area_for_activity(activity), activity.place_td_linx_code, activity.place_name, activity.place_address,
            activity.place_city, activity.place_state, activity.place_zipcode, activity.country, activity.status, activity.created_at,
            activity.created_by, activity.last_modified, activity.modified_by] +
            exporter.custom_fields_to_export_values(activity)
        end
      end
    end

    def data_totals
      @data_totals ||= Hash.new.tap do |totals|
        totals['activities_count'] = collection_search.total
      end
    end

    def authorize_actions
      authorize! :index_results, Activity
    end

    def return_path
      results_reports_path
    end

    def permitted_search_params
      Event.searchable_params + [activity_type: []]
    end
  end
end

app/controllers/results/comments_controller.rb
class Results::CommentsController < FilteredController
  defaults resource_class: ::Event
  respond_to :csv, only: :index

  helper_method :return_path

  private

  def collection_to_csv
    CSV.generate do |csv|
      csv << ['CAMPAIGN NAME', 'VENUE NAME', 'ADDRESS', 'COUNTRY', 'EVENT START DATE', 'EVENT END DATE',
              'CREATED AT', 'CREATED BY', 'LAST MODIFIED', 'MODIFIED BY', 'COMMENT']
      each_collection_item do |event|
        event.comments.each do |comment|
          comment = Csv::CommentPresenter.new(comment, nil)
          csv << [event.campaign_name, event.place_name, event.place_address, event.place_country, event.start_date,
                  event.end_date, comment.created_at, comment.created_by, comment.last_modified, comment.modified_by, comment.content]
        end
      end
    end
  end

  def search_params
    @search_params || (super.tap do |p|
      p[:search_permission] = :index_results
      p[:search_permission_class] = Comment
      p[:with_comments_only] = true unless p.key?(:user) && !p[:user].empty?
    end)
  end

  def authorize_actions
    authorize! :index_results, Comment
  end

  def return_path
    results_reports_path
  end

  def permitted_search_params
    Event.searchable_params
  end
end

app/controllers/results/kpi_reports_controller.rb
class Results::KpiReportsController < ApplicationController
  # before_action :authorize_actions

  def index
    campaigns
    @reports = KpiReport.where(company_user_id: current_company_user).order('created_at DESC')
  end

  def report
    KpiReport.create(company_user: current_company_user, params: params.require(:report).permit({ campaign_id: [] }, :year, :month))
    @report = KpiReport.last
    @report.queue!
  end

  def status
    @reports = KpiReport.where(company_user_id: current_company_user, id: params[:report_ids]) if params[:report_ids].any?
  end

  private

  def campaigns
    @campaigns ||= current_company.campaigns.accessible_by_user(current_company_user).order('name ASC')
  end

  # def authorize_actions
  #   authorize! :kpi_report, Campaign
  # end
end

app/helpers/results/data_extract_helper.rb
module Results
  module DataExtractHelper
    def data_extract_navigation_bar(active)
      data_extract_step_navigation_bar([
        content_tag(:div, 'SELECT REPORT TYPE', class: 'text-large'),
        content_tag(:div, 'SELECT FIELDS', class: 'text-large'),
        content_tag(:div, 'EXPORT & SAVE', class: 'text-large')
      ], active)
    end

    def data_extract_step_navigation_bar(steps, active)
      content_tag :div, class: 'steps-wizard-data-source' do
        content_tag(:div, class: 'row-fluid') do
          steps.each_with_index.map do |step, i|
            step_class = (active == (i + 1) ? 'active' : (active > i ? 'completed' : ''))
            content_tag(:div, class: 'step ' + step_class) do
              content_tag :div, class: 'step-box' do
                content_tag(:div, ((i + 1) >= active ? i + 1 : content_tag(:a, content_tag(:i, '', class: 'icon-checked'), href: form_action(params.merge(step: (i + 1))))), class: 'circle-step ') +
                if (i + 1) < active
                  content_tag(:a, step, href: form_action(params.merge(step: (i + 1))), class: 'step-name')
                else
                  content_tag(:div, step, class: 'step-name')
                end
              end
            end
          end.join.html_safe
        end
      end
    end

    def render_table_cols(columns, step, sort_by, sort_dir, &block)
      content_tag(:thead) do
        content_tag(:tr, class: 'data-extract-head') do
          if columns.present?
            columns.map do |col|
              block_content = capture(col[0], &block) if block_given?
              content_tag(:th, class: 'data-extract-th', data: { name: col[0] }) do
                content_tag(:div, class: 'dropdown') do
                  icon = sort_by == col[0] ? content_tag(:i, '', class: 'icon-checked') : ''
                  content_tag(:span, col[1]) +
                  (if step < 3
                     link_to('', '', title: 'tool', class: 'icon-arrow-down-small dropdown-toggle', data: { name: col[0], toggle: 'dropdown' }) +
                     content_tag(:ul, class: 'dropdown-menu', role: 'menu') do
                       content_tag(:li, icon_sort_asc + link_to(('Sort Ascending' + (sort_dir == 'asc' ? icon : '')).html_safe, '#', class: 'btn-sort-asc btn-sort-table', data: { column: col[0], dir: 'asc' })) +
                       content_tag(:li, icon_sort_desc + link_to(('Sort Descending' + (sort_dir == 'desc' ? icon : '')).html_safe, '#', class: 'btn-sort-desc btn-sort-table', data: { column: col[0], dir: 'desc' })) +
                       content_tag(:li, nil, class: 'divider') +
                       content_tag(:li, icon_visibility_off + link_to('Remove', '#', class: 'btn-remove-column', data: { column: col[0] }))
                     end
                   end)
                end + (block_given? ? block_content : '').html_safe
              end
            end.join.html_safe
          end
        end
      end
    end

    def icon_sort_asc
      content_tag(:i, '', class: 'icon-sort-asc')
    end

    def icon_sort_desc
      content_tag(:i, '', class: 'icon-sort-desc')
    end

    def icon_visibility_off
      content_tag(:i, '', class: 'icon-visibility-off')
    end

    def render_table_rows(rows)
      return unless rows.present?
      rows.map do |row|
        content_tag(:tr) do
          Array(row).map do |field|
            content_tag(:td, field)
          end.join.html_safe
        end
      end.join.html_safe
    end

    def render_available_fields(fields, source)
      content_tag(:ul, class: 'available-field-list', id: 'available-field-list') do
        if fields.present?
          fields.sort.map do |field|
            content_tag(:li, field[1], class: 'available-field', data: { name: field[0], title: render_descripcion_available_field(field[0], source, field[1]) })
          end.join.html_safe
        end
      end
    end

    def render_descripcion_available_field(field, source, title)
      desc = "<p class=\"description-available-field\">#{I18n.t("data_exports.descriptions.#{source}.#{field}", default: title.humanize)}</p>"
    end
  end
end

app/views/results/event_data/_event_data.html.slim
div.resource-item id="event_data_#{event.id}"
  = link_to_if_permitted(:show, Event, event_path(event.id), id: "event-link-#{event.id}", class: 'resource-item-link event-data-row') do
    span.event-info
      b= event.campaign_name
      br>/
      .clean-date
        = format_date_range(event_date(event, :start_at), event_date(event, :end_at), date_separator: ' ')
      = place_address(event.place, false, ', ', ', ')
    .results-box-container
      span.event-data-column.promo-hours-box
        = number_with_precision(event.promo_hours, precision: 1)
      span.event-data-column.impressions-box
        - if event.event_data.present? && event.event_data.impressions.present?
          = number_with_delimiter(event.event_data.impressions)
      span.event-data-column.interactions-box
        - if event.event_data.present? && event.event_data.interactions.present?
          = number_with_delimiter(event.event_data.interactions)
      span.event-data-column.photos-count--box
        - if event.event_data.present? && event.active_photos_count.present?
          = number_with_delimiter(event.active_photos_count)
      span.event-data-column.samples-box
        - if event.event_data.present? && event.event_data.samples.present?
          = number_with_delimiter(event.event_data.samples)
      span.event-data-column.spent-box
        - if event.event_data.present? && event.event_data.spent.present?
          = number_to_currency(event.event_data.spent)
      span.event-data-column.gender-female-box
        - if event.event_data.present? && event.event_data.gender_female.present? && event.event_data.gender_male.present?
          = number_to_percentage(event.event_data.gender_female, precision: 0)
      span.event-data-column.gender-female-box
        - if event.event_data.present? && event.event_data.gender_male.present?
          = number_to_percentage(event.event_data.gender_male, precision: 0)
      span.event-data-column.ethnicity-asian-box
        - if event.event_data.present? && event.event_data.ethnicity_asian.present?
          = number_to_percentage(event.event_data.ethnicity_asian, precision: 0)
      span.event-data-column.ethnicity-black-box
        - if event.event_data.present? && event.event_data.ethnicity_black.present?
          = number_to_percentage(event.event_data.ethnicity_black, precision: 0)
      span.event-data-column.ethnicity-hispanic-box
        - if event.event_data.present? && event.event_data.ethnicity_hispanic.present?
          = number_to_percentage(event.event_data.ethnicity_hispanic, precision: 0)
      span.event-data-column.ethnicity-native-american-box
        - if event.event_data.present? && event.event_data.ethnicity_native_american.present?
          = number_to_percentage(event.event_data.ethnicity_native_american, precision: 0)
      span.event-data-column.ethnicity-white-box
        - if event.event_data.present? && event.event_data.ethnicity_white.present?
          = number_to_percentage(event.event_data.ethnicity_white, precision: 0)
      span.event-data-column.submitted-at-box
        small= l event.submitted_at, format: :long if event.submitted_at.present?
      span.event-data-column.approved-at-box
        small= l event.approved_at, format: :long if event.approved_at.present?
  .clearfix

app/views/results/event_data/_help_tutorial.html.slim
- content_for :help_title do
  | The Results area includes the raw output from all events. You can view photos, surveys, post-event recaps and other data captured across a campaign and export it for additional analysis
.help-overlay-definitions
  div data-target="#application-content" data-intro="Click anywhere or press Esc to close" data-position="top" data-element-class="chardinjs-keep-back" data-tooltip-style="top: -26px;"
  div data-target=".collection-list-horizontal-scroll" data-intro="A summary of key statistics for currently selected events is shown at the top. Clicking on the arrows to the left and right will scroll through additional results fields" data-position="top" data-helper-class="chardinjs-dashed" data-tooltip-style="top: -91px; left: 478px; max-width: 350px; width: 350px;"
  div data-target="#search-box-filter" data-intro="Search for specific events" data-position="bottom" data-tooltip-style="left: 45px; top: 110px; width: 115px; padding: 0px;"
  div data-target=".dates-range-filter" data-intro="Days that have events are indicated with a grey dot. Click and drag to see events for a selected date range" data-position="left" data-helper-class="chardinjs-dashed" data-element-class="chardinjs-keep-back" data-tooltip-style="top: 95px; left: -127px;"
  div data-target=".form-facet-filters" data-intro="Search for specific events by campaign, brand, and location" data-position="left" data-helper-class="chardinjs-dashed" data-element-class="chardinjs-keep-back" data-tooltip-style="top: 200px; left: -127px;"
  div data-target="#save-filters-btn" data-intro='Save frequently used filter combinations by clicking on the "Save Filter" button and use it in later sessions or with other campaigns' data-position="left" data-tooltip-style="top: -65px; left: -124px;"

app/views/results/event_data/_totals.html.slim
.events-box
  .pull-left
    .big-number
      = number_with_precision(data_totals['events_count'], precision: 0, separator: '.', delimiter: ',')
    = 'EVENTS'
.results-box-container
  span.event-data-column.promo-hours-box
    .big-number
      = number_with_precision(data_totals['promo_hours'], precision: 2, separator: '.', delimiter: ',')
    = 'PROMO HOURS'
  span.event-data-column.impressions-box
    .big-number
      = number_with_precision(data_totals['impressions'], precision: 0, separator: '.', delimiter: ',')
    = 'IMPRESSIONS'
  span.event-data-column.interactions-box
    .big-number
      = number_with_precision(data_totals['interactions'], precision: 0, separator: '.', delimiter: ',')
    = 'INTERACTIONS'
  span.event-data-column.active-photos-count-box
    .big-number
      = number_with_precision(data_totals['active_photos_count'], precision: 0, separator: '.', delimiter: ',')
    = 'PHOTOS'
  span.event-data-column.samples-box
    .big-number
      = number_with_precision(data_totals['samples'], precision: 0, separator: '.', delimiter: ',')
    = 'SAMPLED'
  span.event-data-column.spent-box
    .big-number
      = number_to_currency(data_totals['spent'])
    = 'SPENT'
  span.event-data-column.gender-female-box
    .big-number
      = number_to_percentage(data_totals['gender_female'], precision: 0)
    | FEMALE
  span.event-data-column.gender-female-box
    .big-number
      = number_to_percentage(data_totals['gender_male'], precision: 0)
    | MALE
  span.event-data-column.ethnicity-asian-box
    .big-number
      = number_to_percentage(data_totals['ethnicity_asian'], precision: 0)
    | ASIAN
  span.event-data-column.ethnicity-black-box
    .big-number
      = number_to_percentage(data_totals['ethnicity_black'], precision: 0)
    .data-label
      | AFRICAN
      br>/
      | AMERICAN
  span.event-data-column.ethnicity-hispanic-box
    .big-number
      = number_to_percentage(data_totals['ethnicity_hispanic'], precision: 0)
    .data-label
      | HISPANIC
      br>/
      | LATINO
  span.event-data-column.ethnicity-native-american-box
    .big-number
      = number_to_percentage(data_totals['ethnicity_native_american'], precision: 0)
    .data-label
      | NATIVE
      br>/
      | AMERICAN
  span.event-data-column.ethnicity-white-box
    .big-number
      = number_to_percentage(data_totals['ethnicity_white'], precision: 0)
    | WHITE
  span.event-data-column.submitted-at-box
    | SUBMITTED AT
  span.event-data-column.approved-at-box
    | APPROVED AT

app/views/results/event_data/index.html.slim
= user_new_feature('results_event_data') do
  h5 Getting Started: Event Data Report
  a.close.btn-dismiss-alert.icon.icon-close href="#" title="Dismiss"
  a.video-thumbnail href="#" title="Play Video" data-video="//www.youtube.com/embed/qkbS-xRdWtY?rel=0" data-width="640" data-height="360"
    img src="#{image_path('video_arrow.png')}" width="70" height="70" /
  .feature-description
    p
      'The Event Data Report holds all of your post event data. Use this report to keep track of your executed events, review campaign performance, and export raw data to excel. Click on the video to the left for a quick overview or check out our
      a> href="http://support.brandscopic.com" target="_blank" support site
      | for more in depth info.

- content_for :alerts
  div.collection-list-description
    .filter-label
.sidebar#resource-filter-column
  #collection-list-filters
#main.main.with-details-close-bar
  = resource_details_bar("You are viewing the Event Data report. Click to close.")
  .tab-content
    #list-view.tab-pane.active
      #list-tools.row-fluid
        .pull-right
          button.btn.download.xlsx-download-link data-url="#{url_for(format: :csv)}" title="Download" data-disable-with="..."
            span.icon-download
          a.btn.fullscreen.fullscreen-link href="#" data-fullscreen-element='main' title="Fullscreen"
            span.icon-fullscreen
      .collection-list-horizontal-scroll
        #columns-scoller-arrows.hide
          .left-arrow
            a.icon-angle-left
          .right-arrow
            a.icon-angle-right
        #event-data-totals

      #event-data-list.resource-list
        div.placeholder
          p Select any filter to see results

= render partial: 'help_tutorial'

javascript:
  $('#collection-list-filters').filteredList({
    'source': '#{url_for(controller: 'results/event_data', action: :items)}',
    'filtersUrl': '#{filter_url(:events, apply_to: controller_name)}',
    'listContainer': '#event-data-list',
    'sorting': 'start_at',
    'sorting_dir': 'asc',
    'autoLoad': true,
    'includeCalendars': true,
    'selectDefaultDate': false,
    'ytdDatesRange': '#{current_company.ytd_dates_range}',
    'includeAutoComplete': true,
    'autoCompletePath': '#{autocomplete_path(:events, format: :json)}',
    'applyTo': '#{controller_name}',
    'userFilters': #{user_saved_filters(controller_name).to_json.html_safe},
    'defaultParams': '#{j default_params_for_view('status[]=Active')}',
    'emptyStateMessage': '#{j t("results_event_data.empty.line1", scope: :blank_states) }',
    'emptyStateMessageLine2': '#{j t("results_event_data.empty.line2", scope: :blank_states) }',
    'emptyFilterResultsMessage': '#{j t("results_event_data.filters.line1", default: :filters_line1, scope: :blank_states) }',
    'emptyFilterResultsMessageLine2': '#{j t("results_event_data.filters.line2", default: :filters_line2, scope: :blank_states) }',
    'emptyStateImage': '#{asset_path('blank-eventdata.png')}',
    'onChange': function(filterBox){
      $(document).trigger('event-data-filter:changed')
    },
    'onItemsLoad': function(response, page){
      if (response.find('div[data-content="totals-results"]').length > 0){
        $('#columns-scoller-arrows').removeClass('hide')
        $('#event-data-totals').html(response.find('div[data-content="totals-results"]').html())
      }
    },
    'onItemsChange': function(response, page){
      if ($('#event-data-list .resource-item').length > 0) {
        $('#list-tools').show()
      } else {
        $('#list-tools').hide()
      }
    }
  });
  //when clicked right arrow, scroll pane to the right
  $('#columns-scoller-arrows .right-arrow').on('click', function(){
    var $lastItem = $('.results-box-container>span:last-child:first');
    if (($lastItem.offset().left + $lastItem.width()) > $(this).offset().left ) {
      scroll = $('#list-view').data('scroll');
      if (typeof scroll == 'undefined'){
        scroll = 1;
      }
      $('#list-view').addClass('scroll-'+scroll).data('scroll', scroll + 1);
    }
    if (($lastItem.offset().left + $lastItem.width()) <= $(this).offset().left + ($lastItem.width()*2) ) {
      $('#list-view').addClass('scroll-last');
    }
  });
  //when clicked left arrow scroll pane to the  left
  $('#columns-scoller-arrows .left-arrow').on('click', function(){
    scroll = $('#list-view').data('scroll');
    $('#list-view').removeClass('scroll-last')
    if (scroll && scroll > 0){
      scroll = scroll-1;
      $('#list-view').removeClass('scroll-'+scroll).data('scroll', Math.max(scroll,1));
    }
  });
  //when window resized, pane layout
  $(window).bind('resize',function(){
    var $lastItem = $('.results-box-container>span:last-child:first');
    if ($lastItem.length > 0){
      if (($lastItem.offset().left + $lastItem.width()) <= $('#columns-scoller-arrows .right-arrow').offset().left ) {
         $('#list-view').addClass('scroll-last');
      } else {
        $('#list-view').removeClass('scroll-last');
      }
    }
  })

app/views/results/event_data/items.html.slim
div data-content="items" data-existing-total="#{collection_total_count}" data-total="#{collection_count}" data-pages="#{total_pages}" data-page="#{params[:page] || 1}"

  = render collection: collection, partial: 'event_data', as: :event

- if params[:page].nil? || params[:page] == '1'
  div data-content="totals-results"
    = render 'totals'

  div data-content="filters-description"
    = describe_filters('result')