config/routes.rb
Brandscopic::Application.routes.draw do

  mount Nkss::Engine => '/styleguides' if Rails.env.development?
  apipie if ENV['WEB']

  # Redirect old urls to new ones
  get '/results/gva', to: redirect('/analysis/gva')
  get '/results/event_status', to: redirect('/analysis/event_status')
  get '/results/attendance', to: redirect('/analysis/attendance')

  concern :deactivatable do
    get :deactivate, on: :member
    get :activate, on: :member
  end

  concern :filterable do
    get :items, on: :collection, format: :html
  end

  concern :commentable do
    resources :comments, only: [:index, :create, :update, :destroy]
  end

  concern :api_attachable do
    get :form, on: :collection
  end

  concern :form_field_exportable do
    get :form, action: :export_fieldable, on: :member
    get :export_results, on: :member
  end

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create'
        delete 'sessions' => 'sessions#destroy'

        get '/companies' => 'users#companies'
        resources :users, only: [:index, :update, :show] do
          collection do
            match 'password/new_password', to: 'users#new_password', via: :post
            get :permissions
            get :notifications
          end
        end
        resources :activities, only: [:new, :show]

        resources :filters, only: [:show]

        resources :events, only: [:index, :show, :create, :update], concerns: [:commentable] do
          get :status_facets, on: :collection
          get :requiring_attention, on: :collection
          post :filter, to: 'events#index', on: :collection
          resources :photos, only: [:index, :create, :update], concerns: [:api_attachable]
          resources :documents, only: [:index, :create, :update], concerns: [:api_attachable]
          resources :event_expenses, only: [:index, :create, :destroy, :update], concerns: [:api_attachable]
          resources :tasks, only: [:index, :create]
          resources :surveys,  only: [:index, :create, :update, :show] do
            get :brands, on: :collection
          end
          resources :invites, only: [:index, :show, :create, :update]
          resources :activities, only: [:index, :create, :update], concerns: [:deactivatable, :api_attachable] do
            get :deactivate, on: :member
          end
          get :autocomplete,   on: :collection
          member do
            put :submit
            put :reject
            put :approve
            get :results
            get :members
            post :members, to: 'events#add_member'
            delete :members, to: 'events#delete_member'
            get :assignable_members
            get :contacts
            post :contacts, to: 'events#add_contact'
            delete :contacts, to: 'events#delete_contact'
            get :assignable_contacts
            get :details_counters
          end
        end

        resources :campaigns, only: [] do
          collection do
            get :all
            get :overall_stats
          end
          resources :activity_types, only: [:index]
          resources :brands, only: [:index]
          get :stats, on: :member
          get :events, on: :member
          get :expense_categories, on: :member
        end

        resources :activity_types, only: [:index] do
          member do
            get :campaigns
          end
        end

        resources :venues, only: [:index, :show, :create] do
          get :search, on: :collection
          get :types, on: :collection
          get :autocomplete, on: :collection
          resources :invites, only: [:index, :show, :create, :update]
          resources :activities, only: [:index, :create, :update] do
            get :deactivate, on: :member
          end
          member do
            get :analysis
            get :photos
            get :comments
          end
        end

        resources :areas, only: [:index] do
          get :cities, on: :member
        end

        resources :brands, only: [:index] do
          get :marques, on: :member
        end

        resources :countries, only: [:index] do
          get :states, on: :member
        end

        resources :contacts, only: [:index, :create, :update, :show]

        resources :tasks, only: [:update, :create, :show], concerns: [:commentable] do
          collection do
            get :mine, action: :index, defaults: { scope: 'user' }, constraints: { scope: 'user' }
            get :team, action: :index, defaults: { scope: 'teams' }, constraints: { scope: 'teams' }
          end
        end

        namespace :brand_ambassadors do
          resources :visits, only: [:index, :create, :update, :show] do
            get :types, on: :collection
            get :events, on: :member
          end
          resources :documents, only: [:create, :update, :destroy, :index]
        end
      end
    end
  end

  if ENV['WEB']
    require 'sidekiq/web'
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    authenticate :admin_user do
      mount Sidekiq::Web => '/_bgjobs' unless Rails.env.test?
    end
  end

  devise_for :users, controllers: { invitations: 'invitations', passwords: 'passwords' }

  devise_scope :user do
    put '/users/confirmation', to: 'confirmations#update'
    get '/users/invitation/resend', to: 'invitations#resend'
    get '/users/invitation/renew', to: 'invitations#renew'
    post '/users/invitation/resend', to: 'invitations#send_invite'
    get '/users/password/thanks', to: 'passwords#thanks', as: :passwords_thanks
  end

  put '/users/dismiss_alert', to: 'company_users#dismiss_alert'

  get 'select-company/:company_id', to: 'company_users#select_company', as: :select_company, constraints: { company_id: /[0-9]+/ }
  put 'login-as', to: 'company_users#select_custom_user', as: :select_custom_user

  resources :countries, only: [] do
    get :states, on: :collection
    get :cities, on: :member
  end

  get '/notifications.json', to: 'company_users#notifications', format: :json

  get 'exports/:download_id/status', to: 'company_users#export_status', as: :export_status, format: :json

  resources :goals, only: [:create, :update]

  resources :photos, only: [:show]

  # /filters/events /filters/campaigns etc
  resources :filters, only: [:show] do
    get :expand, on: :collection
  end

  # /autocomplete/events /autocomplete/campaigns etc
  resources :autocomplete, only: [:show]

  namespace :results do
    resources :event_data, only: [:index], concerns: [:filterable]
    resources :comments, only: [:index], concerns: [:filterable]
    resources :photos, only: [:index], concerns: [:filterable] do
      post 'downloads', to: 'photos#new_download', on: :collection, format: :js
      get 'downloads/:download_id', to: 'photos#download', on: :collection, as: :download, format: :js
      get 'downloads/:download_id/status', to: 'photos#download_status', on: :collection, as: :download_status, format: :json
    end
    resources :activities, only: [:index], concerns: [:filterable]
    resources :expenses, only: [:index], concerns: [:filterable]
    resources :surveys, only: [:index], concerns: [:filterable]

    # resources :attendance, only: [:index] do
    # end

    resources :reports, only: [:index, :new, :create, :edit, :update, :show],
                        concerns: [:deactivatable] do
      get :build, on: :member
      get :rows, on: :member
      get :filters, on: :member
      get :share, to: 'reports#share_form', on: :member
      post :preview, on: :member
    end

    resources :data_extracts, only: [:new, :create, :show, :edit, :update] do
      get :preview, on: :collection
      get :save, on: :collection
      get :available_fields, on: :collection
      get :items, on: :collection
      get :deactivate, on: :member
      get :activate, on: :member
    end

    # For The KPI report
    get :kpi_report, to: 'kpi_reports#index'

    post :kpi_report, to: 'kpi_reports#report'
    get :kpi_report_status, to: 'kpi_reports#status'

  end

  namespace :analysis do
    resources :trends, only: [] do
      collection do
        get :sources
        get :questions
        get :results
        get :items
        get :filters
        get :search
      end
      get 't/:term', on: :collection, action: :show
      get 't/:term/:action', on: :collection
    end

    get 'attendance/map', to: 'attendance#map', as: :attendance_map
    get 'attendance', to: 'attendance#index', as: :attendance

    get :gva, to: 'gva#index'
    post :gva, to: 'gva#report'
    get :report_groups, to: 'gva#report_groups'

    get :event_status, to: 'event_status#index'
    post :event_status, to: 'event_status#report'

    get :campaigns_report, to: 'campaigns_report#index'
    post :campaigns_report, to: 'campaigns_report#report'

    get :staff_report, to: 'staff_report#index'
    post :staff_report, to: 'staff_report#report'

    get :campaign_summary_report, to: 'campaign_summary_report#index'
    get :campaign_summary_report_show_all, to: 'campaign_summary_report#show_all'
    post :campaign_summary_report, to: 'campaign_summary_report#report'
    get :campaign_summary_report_export, to: 'campaign_summary_report#export_results'
    get :campaign_summary_report_items, to: 'campaign_summary_report#items'
    get :campaign_summary_report_result, to: 'campaign_summary_report#result'

    get '/', to: 'analysis#index'
  end

  scope '/research' do
    resources :venues, only: [:index, :show], concerns: [:filterable] do
      member do
        match 'areas/:area_id' => 'venues#delete_area', via: :delete, as: :delete_area
        match 'areas/select' => 'venues#select_areas', via: :get, as: :select_areas
        match 'areas/add' => 'venues#add_areas', via: :post, as: :add_area
        match 'areas' => 'venues#areas', via: :get, as: :areas
      end
      resources :events, only: [:new, :create]

app/controllers/activities_controller.rb
# Activities Controller class
#
# This class handle the requests for managing the Activities
class ActivitiesController < FilteredController
  belongs_to :venue, :event, polymorphic: true, optional: true
  respond_to :js, only: [:new]
  custom_actions member: [:form]

  before_action :copy_of_destroyed, only: [:destroy]

  layout 'empty', except: :show

  # This helper provide the methods to export HTML to PDF
  include ExportableForm

  # This helper provide the methods to activate/deactivate the resource
  include DeactivableController

  helper_method :assignable_users, :activity_types

  def new
    if params[:activity] && params[:activity][:activity_type_id]
      build_resource
      @brands = Brand.accessible_by_user(current_company_user).order(:name)
    elsif request.format.js?
      render partial: 'form_dialog', locals: { form_partial: 'select_activity_type_form' }
    end
  end

  def thanks
    @activity_type = current_company.activity_types.find(params[:activity_type_id])
  end

  def create
    create! do |success, _failure|
      success.html do
        flash.clear
        session["activity_create_#{params[:form_id]}"] ||= 0
        session["activity_create_#{params[:form_id]}"] += 1
        redirect_to url_for(action: :thanks, activity_type_id: resource.activity_type_id, form_id: params[:form_id])
      end
    end
  end

  def update
    update! do |success, _failure|
      success.html do
        flash.clear
        redirect_to url_for(resource.activitable) + '#activities-list'
      end
    end
  end

  protected

  def copy_of_destroyed
    @activity = resource
  end

  def pdf_form_file_name
    "#{resource.activity_type_name.parameterize}-#{Time.now.strftime('%Y%m%d%H%M%S')}.pdf"
  end

  def assignable_users
    current_company.company_users.active.for_dropdown
  end

  def activity_types
    types =
      if parent.is_a?(Event)
        parent.campaign.activity_types.order('activity_types.name ASC')
      else
        current_company.activity_types.active.order(:name)
      end.pluck(:name, :id)
  end

  # Because there is no collection path, try to return a path
  # based on the current activity or the events_path
  def collection_path
    if params[:id].present?
      url_for(resource.activitable)
    else
      events_path
    end
  end

  def permitted_params
    params.permit(activity: [
      :activity_type_id, {
        results_attributes: [:id, :form_field_id, :value, { value: [] }, :_destroy] },
      :campaign_id, :company_user_id, :activity_date])[:activity].tap do |whielisted|
      unless whielisted.nil? || whielisted[:results_attributes].nil?
        whielisted[:results_attributes].each do |k, value|
          value[:value] = params[:activity][:results_attributes][k][:value]
        end
      end
    end
  end
end

app/controllers/results/kpi_reports_controller.rb
class Results::KpiReportsController < ApplicationController
  # before_action :authorize_actions

  def index
    campaigns
    @reports = KpiReport.where(company_user_id: current_company_user).order('created_at DESC')
  end

  def report
    KpiReport.create(company_user: current_company_user, params: params.require(:report).permit({ campaign_id: [] }, :year, :month))
    @report = KpiReport.last
    @report.queue!
  end

  def status
    @reports = KpiReport.where(company_user_id: current_company_user, id: params[:report_ids]) if params[:report_ids].any?
  end

  private

  def campaigns
    @campaigns ||= current_company.campaigns.accessible_by_user(current_company_user).order('name ASC')
  end

  # def authorize_actions
  #   authorize! :kpi_report, Campaign
  # end
end

app/helpers/results/data_extract_helper.rb
module Results
  module DataExtractHelper
    def data_extract_navigation_bar(active)
      data_extract_step_navigation_bar([
        content_tag(:div, 'SELECT REPORT TYPE', class: 'text-large'),
        content_tag(:div, 'SELECT FIELDS', class: 'text-large'),
        content_tag(:div, 'EXPORT & SAVE', class: 'text-large')
      ], active)
    end

    def data_extract_step_navigation_bar(steps, active)
      content_tag :div, class: 'steps-wizard-data-source' do
        content_tag(:div, class: 'row-fluid') do
          steps.each_with_index.map do |step, i|
            step_class = (active == (i + 1) ? 'active' : (active > i ? 'completed' : ''))
            content_tag(:div, class: 'step ' + step_class) do
              content_tag :div, class: 'step-box' do
                content_tag(:div, ((i + 1) >= active ? i + 1 : content_tag(:a, content_tag(:i, '', class: 'icon-checked'), href: form_action(params.merge(step: (i + 1))))), class: 'circle-step ') +
                if (i + 1) < active
                  content_tag(:a, step, href: form_action(params.merge(step: (i + 1))), class: 'step-name')
                else
                  content_tag(:div, step, class: 'step-name')
                end
              end
            end
          end.join.html_safe
        end
      end
    end

    def render_table_cols(columns, step, sort_by, sort_dir, &block)
      content_tag(:thead) do
        content_tag(:tr, class: 'data-extract-head') do
          if columns.present?
            columns.map do |col|
              block_content = capture(col[0], &block) if block_given?
              content_tag(:th, class: 'data-extract-th', data: { name: col[0] }) do
                content_tag(:div, class: 'dropdown') do
                  icon = sort_by == col[0] ? content_tag(:i, '', class: 'icon-checked') : ''
                  content_tag(:span, col[1]) +
                  (if step < 3
                     link_to('', '', title: 'tool', class: 'icon-arrow-down-small dropdown-toggle', data: { name: col[0], toggle: 'dropdown' }) +
                     content_tag(:ul, class: 'dropdown-menu', role: 'menu') do
                       content_tag(:li, icon_sort_asc + link_to(('Sort Ascending' + (sort_dir == 'asc' ? icon : '')).html_safe, '#', class: 'btn-sort-asc btn-sort-table', data: { column: col[0], dir: 'asc' })) +
                       content_tag(:li, icon_sort_desc + link_to(('Sort Descending' + (sort_dir == 'desc' ? icon : '')).html_safe, '#', class: 'btn-sort-desc btn-sort-table', data: { column: col[0], dir: 'desc' })) +
                       content_tag(:li, nil, class: 'divider') +
                       content_tag(:li, icon_visibility_off + link_to('Remove', '#', class: 'btn-remove-column', data: { column: col[0] }))
                     end
                   end)
                end + (block_given? ? block_content : '').html_safe
              end
            end.join.html_safe
          end
        end
      end
    end

    def icon_sort_asc
      content_tag(:i, '', class: 'icon-sort-asc')
    end

    def icon_sort_desc
      content_tag(:i, '', class: 'icon-sort-desc')
    end

    def icon_visibility_off
      content_tag(:i, '', class: 'icon-visibility-off')
    end

    def render_table_rows(rows)
      return unless rows.present?
      rows.map do |row|
        content_tag(:tr) do
          Array(row).map do |field|
            content_tag(:td, field)
          end.join.html_safe
        end
      end.join.html_safe
    end

    def render_available_fields(fields, source)
      content_tag(:ul, class: 'available-field-list', id: 'available-field-list') do
        if fields.present?
          fields.sort.map do |field|
            content_tag(:li, field[1], class: 'available-field', data: { name: field[0], title: render_descripcion_available_field(field[0], source, field[1]) })
          end.join.html_safe
        end
      end
    end

    def render_descripcion_available_field(field, source, title)
      desc = "<p class=\"description-available-field\">#{I18n.t("data_exports.descriptions.#{source}.#{field}", default: title.humanize)}</p>"
    end
  end
end

app/views/results/activities/_activity.html.slim
.resource-item id="activity_#{activity.id}"
  = link_to_if_permitted(:show, Activity, activity_path(activity), title: 'Activity Details', class: 'resource-item-link')
    .span4
      .text-large= activity.activity_type.name
      = activity.company_user.full_name
    .span3
      .date= format_date(activity.activity_date)
    .span5
      .text-large= activity.campaign_name
      = activity.place_name
      br
      = activity.place_formatted_address

app/views/results/activities/_help_tutorial.slim
.help-overlay-definitions
  div data-target="#application-content" data-intro="Click anywhere or press Esc to close" data-position="top" data-element-class="chardinjs-keep-back" data-tooltip-style="top: -20px;"

    //For list mode

  div data-target="#search-box-filter" data-intro="Search for specific events" data-position="top" data-tooltip-style="top: -55px; right: 12px; height: 52px; max-width: 210px;"

  div data-target="#btn-export" data-intro="Export activities to Excel or PDF" data-position="left" data-tooltip-style="top: -10px; left: -140px; height: 52px; max-width: 210px;"

  div data-target=".dates-range-filter" data-intro="Days that have events scheduled are indicated with a grey dot. Click and drag to see events for a selected date range" data-position="left" data-helper-class="chardinjs-dashed" data-element-class="chardinjs-keep-back" data-tooltip-style="top: 94px; left: -140px; height: 52px; max-width: 210px;"

  div data-target=".form-facet-filters" data-intro="Filter by multiple criteria" data-position="left" data-helper-class="chardinjs-dashed" data-element-class="chardinjs-keep-back" data-tooltip-style="top: 40px; left: -130px; height: 52px; max-width: 210px;"

  div data-target="#save-filters-btn" data-intro="Save frequently used filter combinations by clicking the Save button and use in later sessions" data-position="left" data-tooltip-style="top: -18px; left: -140px; height: 52px; max-width: 210px;"

app/views/results/activities/_totals.html.slim
.activities-box
  .pull-left
    .big-number
      = number_with_precision(data_totals['activities_count'], precision: 0, separator: '.', delimiter: ',')
    = 'ACTIVITIES'

app/views/results/activities/index.html.slim
= user_new_feature 'results_activity_data'

- content_for :alerts
  div.collection-list-description
    .filter-label
.sidebar#resource-filter-column
  #collection-list-filters
#main.main.with-details-close-bar
  = resource_details_bar("You are viewing the Activity Data report. Click to close.")
  .tab-content
    #list-view.tab-pane.active
      #list-tools.row-fluid.text-right
        .dropdown.btn-download#btn-export
          a.btn.dropdown-toggle href="#" data-toggle="dropdown" data-target="#" title="Download"
            i.icon-download
            i.icon-arrow-down-small
          ul.dropdown-menu.download-options-menu role="menu" aria-labelledby="dLabel"
            li
              a.xlsx-download-link href="#" role="menuitem" data-url="#{results_activities_path(format: :csv)}"
                | Download as CSV
            li
              a#pdf-export.xlsx-download-link href="#" role="menuitem" data-url="#{results_activities_path(format: :pdf)}"
                | Download as PDF
      .collection-list-horizontal-scroll
        #columns-scoller-arrows.hide
          .left-arrow
            a.icon-angle-left
          .right-arrow
            a.icon-angle-right
        #activity-data-totals

  div.resource-list.without-actions id="#{controller_name}-list"

= render partial: 'help_tutorial'

javascript:
  $('#collection-list-filters').filteredList({
    'source': '#{url_for(controller: 'results/activities', action: :items)}',
    'filtersUrl': '#{filter_url(:activities, apply_to: controller_name)}',
    'listContainer' : '##{controller_name}-list',
    'sorting': 'activity_date',
    'sorting_dir': 'asc',
    'autoLoad': true,
    'applyTo': '#{controller_name}',
    'userFilters': #{user_saved_filters(controller_name).to_json.html_safe},
    'includeCalendars': true,
    'selectDefaultDate': false,
    'ytdDatesRange': '#{current_company.ytd_dates_range}',
    'includeAutoComplete': true,
    'autoCompletePath': '#{autocomplete_path(:activities, format: :json)}',
    'defaultParams': '#{j default_params_for_view('status[]=Active')}',
    'emptyStateMessage': '#{j t("results_activities.empty.line1", scope: :blank_states) }',
    'emptyStateMessageLine2': '#{j t("results_activities.empty.line2", scope: :blank_states) }',
    'emptyFilterResultsMessage': '#{j t("results_activities.filters.line1", default: :filters_line1, scope: :blank_states) }',
    'emptyFilterResultsMessageLine2': '#{j t("results_activities.filters.line2", default: :filters_line2, scope: :blank_states) }',
    'emptyStateImage': '#{asset_path('blank-activity.png')}',
    'onChange': function (filterBox) {
      $(document).trigger('activity-data-filter:changed')
    },
    'onItemsLoad': function(response, page){
      if (response.find('div[data-content="totals-results"]').length > 0){
        $('#columns-scoller-arrows').removeClass('hide')
        $('#activity-data-totals').html(response.find('div[data-content="totals-results"]').html())
      }
    },
    'onItemsChange': function(response, page){
      if ($('#activities-list .resource-item').length > 0) {
        $('#list-tools').show()
      } else {
        $('#list-tools').hide()
      }
    }
  });
  //when clicked right arrow, scroll pane to the right
  $('#columns-scoller-arrows .right-arrow').on('click', function () {
    var $lastItem = $('.results-box-container>span:last-child:first');
    if (($lastItem.offset().left + $lastItem.width()) > $(this).offset().left) {
      scroll = $('#list-view').data('scroll');
      if (typeof scroll == 'undefined') {
        scroll = 1;
      }
      $('#list-view').addClass('scroll-' + scroll).data('scroll', scroll + 1);
    }
    if (($lastItem.offset().left + $lastItem.width()) <= $(this).offset().left + ($lastItem.width() * 2)) {
      $('#list-view').addClass('scroll-last');
    }
  });
  //when clicked left arrow scroll pane to the  left
  $('#columns-scoller-arrows .left-arrow').on('click', function () {
    scroll = $('#list-view').data('scroll');
    $('#list-view').removeClass('scroll-last')
    if (scroll && scroll > 0) {
      scroll = scroll - 1;
      $('#list-view').removeClass('scroll-' + scroll).data('scroll', Math.max(scroll, 1));
    }
  });
  //when window resized, pane layout
  $(window).bind('resize', function () {
    var $lastItem = $('.results-box-container>span:last-child:first');
    if ($lastItem.length > 0) {
      if (($lastItem.offset().left + $lastItem.width()) <= $('#columns-scoller-arrows .right-arrow').offset().left) {
        $('#list-view').addClass('scroll-last');
      } else {
        $('#list-view').removeClass('scroll-last');
      }
    }
  })

app/views/results/activities/items.html.slim
div data-content="items" data-existing-total="#{collection_total_count}" data-total="#{collection_count}" data-pages="#{total_pages}" data-page="#{params[:page] || 1}"
  = render collection

- if params[:page].nil? || params[:page] == '1'
  div data-content="totals-results"
    = render 'totals'

- if params[:page].nil? || params[:page] == '1'
  div data-content="filters-description"
    = describe_filters