config/routes.rb
Brandscopic::Application.routes.draw do

  mount Nkss::Engine => '/styleguides' if Rails.env.development?
  apipie if ENV['WEB']

  # Redirect old urls to new ones
  get '/results/gva', to: redirect('/analysis/gva')
  get '/results/event_status', to: redirect('/analysis/event_status')
  get '/results/attendance', to: redirect('/analysis/attendance')

  concern :deactivatable do
    get :deactivate, on: :member
    get :activate, on: :member
  end

  concern :filterable do
    get :items, on: :collection, format: :html
  end

  concern :commentable do
    resources :comments, only: [:index, :create, :update, :destroy]
  end

  concern :api_attachable do
    get :form, on: :collection
  end

  concern :form_field_exportable do
    get :form, action: :export_fieldable, on: :member
    get :export_results, on: :member
  end

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create'
        delete 'sessions' => 'sessions#destroy'

        get '/companies' => 'users#companies'
        resources :users, only: [:index, :update, :show] do
          collection do
            match 'password/new_password', to: 'users#new_password', via: :post
            get :permissions
            get :notifications
          end
        end
        resources :activities, only: [:new, :show]

        resources :filters, only: [:show]

        resources :events, only: [:index, :show, :create, :update], concerns: [:commentable] do
          get :status_facets, on: :collection
          get :requiring_attention, on: :collection
          post :filter, to: 'events#index', on: :collection
          resources :photos, only: [:index, :create, :update], concerns: [:api_attachable]
          resources :documents, only: [:index, :create, :update], concerns: [:api_attachable]
          resources :event_expenses, only: [:index, :create, :destroy, :update], concerns: [:api_attachable]
          resources :tasks, only: [:index, :create]
          resources :surveys,  only: [:index, :create, :update, :show] do
            get :brands, on: :collection
          end
          resources :invites, only: [:index, :show, :create, :update]
          resources :activities, only: [:index, :create, :update], concerns: [:deactivatable, :api_attachable] do
            get :deactivate, on: :member
          end
          get :autocomplete,   on: :collection
          member do
            put :submit
            put :reject
            put :approve
            get :results
            get :members
            post :members, to: 'events#add_member'
            delete :members, to: 'events#delete_member'
            get :assignable_members
            get :contacts
            post :contacts, to: 'events#add_contact'
            delete :contacts, to: 'events#delete_contact'
            get :assignable_contacts
            get :details_counters
          end
        end

        resources :campaigns, only: [] do
          collection do
            get :all
            get :overall_stats
          end
          resources :activity_types, only: [:index]
          resources :brands, only: [:index]
          get :stats, on: :member
          get :events, on: :member
          get :expense_categories, on: :member
        end

        resources :activity_types, only: [:index] do
          member do
            get :campaigns
          end
        end

        resources :venues, only: [:index, :show, :create] do
          get :search, on: :collection
          get :types, on: :collection
          get :autocomplete, on: :collection
          resources :invites, only: [:index, :show, :create, :update]
          resources :activities, only: [:index, :create, :update] do
            get :deactivate, on: :member
          end
          member do
            get :analysis
            get :photos
            get :comments
          end
        end

        resources :areas, only: [:index] do
          get :cities, on: :member
        end

        resources :brands, only: [:index] do
          get :marques, on: :member
        end

        resources :countries, only: [:index] do
          get :states, on: :member
        end

        resources :contacts, only: [:index, :create, :update, :show]

        resources :tasks, only: [:update, :create, :show], concerns: [:commentable] do
          collection do
            get :mine, action: :index, defaults: { scope: 'user' }, constraints: { scope: 'user' }
            get :team, action: :index, defaults: { scope: 'teams' }, constraints: { scope: 'teams' }
          end
        end

        namespace :brand_ambassadors do
          resources :visits, only: [:index, :create, :update, :show] do
            get :types, on: :collection
            get :events, on: :member
          end
          resources :documents, only: [:create, :update, :destroy, :index]
        end
      end
    end
  end

  if ENV['WEB']
    require 'sidekiq/web'
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    authenticate :admin_user do
      mount Sidekiq::Web => '/_bgjobs' unless Rails.env.test?
    end
  end

  devise_for :users, controllers: { invitations: 'invitations', passwords: 'passwords' }

  devise_scope :user do
    put '/users/confirmation', to: 'confirmations#update'
    get '/users/invitation/resend', to: 'invitations#resend'
    get '/users/invitation/renew', to: 'invitations#renew'
    post '/users/invitation/resend', to: 'invitations#send_invite'
    get '/users/password/thanks', to: 'passwords#thanks', as: :passwords_thanks
  end

  put '/users/dismiss_alert', to: 'company_users#dismiss_alert'

  get 'select-company/:company_id', to: 'company_users#select_company', as: :select_company, constraints: { company_id: /[0-9]+/ }
  put 'login-as', to: 'company_users#select_custom_user', as: :select_custom_user

  resources :countries, only: [] do
    get :states, on: :collection
    get :cities, on: :member
  end

  get '/notifications.json', to: 'company_users#notifications', format: :json

  get 'exports/:download_id/status', to: 'company_users#export_status', as: :export_status, format: :json

  resources :goals, only: [:create, :update]

  resources :photos, only: [:show]

  # /filters/events /filters/campaigns etc
  resources :filters, only: [:show] do
    get :expand, on: :collection
  end

  # /autocomplete/events /autocomplete/campaigns etc
  resources :autocomplete, only: [:show]

  namespace :results do
    resources :event_data, only: [:index], concerns: [:filterable]
    resources :comments, only: [:index], concerns: [:filterable]
    resources :photos, only: [:index], concerns: [:filterable] do
      post 'downloads', to: 'photos#new_download', on: :collection, format: :js
      get 'downloads/:download_id', to: 'photos#download', on: :collection, as: :download, format: :js
      get 'downloads/:download_id/status', to: 'photos#download_status', on: :collection, as: :download_status, format: :json
    end
    resources :activities, only: [:index], concerns: [:filterable]
    resources :expenses, only: [:index], concerns: [:filterable]
    resources :surveys, only: [:index], concerns: [:filterable]

    # resources :attendance, only: [:index] do
    # end

    resources :reports, only: [:index, :new, :create, :edit, :update, :show],
                        concerns: [:deactivatable] do
      get :build, on: :member
      get :rows, on: :member
      get :filters, on: :member
      get :share, to: 'reports#share_form', on: :member
      post :preview, on: :member
    end

    resources :data_extracts, only: [:new, :create, :show, :edit, :update] do
      get :preview, on: :collection
      get :save, on: :collection
      get :available_fields, on: :collection
      get :items, on: :collection
      get :deactivate, on: :member
      get :activate, on: :member
    end

    # For The KPI report
    get :kpi_report, to: 'kpi_reports#index'

    post :kpi_report, to: 'kpi_reports#report'
    get :kpi_report_status, to: 'kpi_reports#status'

  end

  namespace :analysis do
    resources :trends, only: [] do
      collection do
        get :sources
        get :questions
        get :results
        get :items
        get :filters
        get :search
      end
      get 't/:term', on: :collection, action: :show
      get 't/:term/:action', on: :collection
    end

    get 'attendance/map', to: 'attendance#map', as: :attendance_map
    get 'attendance', to: 'attendance#index', as: :attendance

    get :gva, to: 'gva#index'
    post :gva, to: 'gva#report'
    get :report_groups, to: 'gva#report_groups'

    get :event_status, to: 'event_status#index'
    post :event_status, to: 'event_status#report'

    get :campaigns_report, to: 'campaigns_report#index'
    post :campaigns_report, to: 'campaigns_report#report'

    get :staff_report, to: 'staff_report#index'
    post :staff_report, to: 'staff_report#report'

    get :campaign_summary_report, to: 'campaign_summary_report#index'
    get :campaign_summary_report_show_all, to: 'campaign_summary_report#show_all'
    post :campaign_summary_report, to: 'campaign_summary_report#report'
    get :campaign_summary_report_export, to: 'campaign_summary_report#export_results'
    get :campaign_summary_report_items, to: 'campaign_summary_report#items'
    get :campaign_summary_report_result, to: 'campaign_summary_report#result'

    get '/', to: 'analysis#index'
  end

  scope '/research' do
    resources :venues, only: [:index, :show], concerns: [:filterable] do
      member do
        match 'areas/:area_id' => 'venues#delete_area', via: :delete, as: :delete_area
        match 'areas/select' => 'venues#select_areas', via: :get, as: :select_areas
        match 'areas/add' => 'venues#add_areas', via: :post, as: :add_area
        match 'areas' => 'venues#areas', via: :get, as: :areas
      end
      resources :events, only: [:new, :create]

app/models/data_extract/survey.rb
# == Schema Information
#
# Table name: data_extracts
#
#  id               :integer          not null, primary key
#  type             :string(255)
#  company_id       :integer
#  active           :boolean          default("true")
#  sharing          :string(255)
#  name             :string(255)
#  description      :text
#  columns          :text
#  created_by_id    :integer
#  updated_by_id    :integer
#  created_at       :datetime
#  updated_at       :datetime
#  default_sort_by  :string(255)
#  default_sort_dir :string(255)
#  params           :text
#

class DataExtract::Survey < DataExtract
  define_columns []
end

app/models/survey.rb
# == Schema Information
#
# Table name: surveys
#
#  id            :integer          not null, primary key
#  event_id      :integer
#  created_by_id :integer
#  updated_by_id :integer
#  active        :boolean          default("true")
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Survey < ActiveRecord::Base
  belongs_to :event

  has_many :surveys_answers, autosave: true, inverse_of: :survey

  accepts_nested_attributes_for :surveys_answers

  delegate :company_id, to: :event

  after_save :reindex_event

  def brands
    event.campaign.survey_brands
  end

  def age
    answer = surveys_answers.select { |a| a.kpi_id == Kpi.age.id }.first
    answer.segment.text unless answer.nil? || answer.segment.nil?
  end

  def gender
    answer = surveys_answers.select { |a| a.kpi_id == Kpi.gender.id }.first
    answer.segment.text unless answer.nil? || answer.segment.nil?
  end

  def ethnicity
    answer = surveys_answers.select { |a| a.kpi_id == Kpi.ethnicity.id }.first
    answer.segment.text unless answer.nil? || answer.segment.nil?
  end

  def activate!
    update_attribute :active, true
  end

  def deactivate!
    update_attribute :active, false
  end

  def answer_for(question_id, brand_id, kpi_id = nil)
    if kpi_id.nil?
      surveys_answers.select { |a| a.question_id == question_id && a.brand_id == brand_id }.first || surveys_answers.build(question_id: question_id, brand_id: brand_id)
    else
      surveys_answers.select { |a| a.question_id == question_id && a.kpi_id == kpi_id }.first || surveys_answers.build(question_id: question_id, kpi_id: kpi_id)
    end
  end

  protected

  def reindex_event
    # if this is the first survey for the event, then reindex it to set the flag "has_surveys" true
    if event.present? && event.surveys.count == 1
      Sunspot.index event
    end
  end
end

app/controllers/results/surveys_controller.rb
class Results::SurveysController < FilteredController
  defaults resource_class: ::Event
  respond_to :xls, only: :index

  helper_method :expenses_total, :return_path

  private

  def collection_to_csv
    CSV.generate do |csv|
      csv << ['DESCRIPTION', 'CAMPAIGN NAME', 'VENUE NAME', 'ADDRESS', 'EVENT START DATE', 'EVENT END DATE', 'SURVEY CREATED DATE']
      each_collection_item do |event|
        event.surveys.each do |survey|
          survey = Csv::SurveyPresenter.new(survey, view_context)
          desc = []
          desc.push "#{survey.age} year old" if survey.age
          desc.push survey.ethnicity
          desc.push survey.gender
          csv << [desc.join(','), event.campaign_name, event.place_name, survey.place_address(event),
                  survey.event_start_date, survey.event_end_date, survey.created_date]
        end
      end
    end
  end

  def search_params
    @search_params || (super.tap do |p|
      p[:with_surveys_only] = true unless p.key?(:user) && !p[:user].empty?
      p[:search_permission] = :index_results
      p[:search_permission_class] = Survey
    end)
  end

  def authorize_actions
    authorize! :index_results, Survey
  end

  def return_path
    results_reports_path
  end

  def permitted_search_params
    Event.searchable_params
  end
end

app/controllers/surveys_controller.rb
class SurveysController < FilteredController
  belongs_to :event
  respond_to :js, only: [:new, :create, :edit, :update]
  actions :new, :create, :edit, :update

  include DeactivableController

  protected

  def permitted_params
    params.permit(survey: { surveys_answers_attributes: [:id, :brand_id, :question_id, :answer, :kpi_id] })[:survey]
  end
end

app/views/surveys/_form.html.slim
#survey-form
  = simple_nested_form_for([parent, resource], html: { :multipart => true, class: 'survey_form' }, remote: true) do |f|
    = f.error_notification
    .form-inputs
      fieldset
        legend Demographics
        - Kpi.where('module' => 'demographics' ).each do |kpi|
          .demograpics-module
            = f.simple_fields_for :surveys_answers, resource.answer_for(1, nil, kpi.id) do |qf|
              = qf.hidden_field :kpi_id
              = qf.hidden_field :question_id
              = qf.input :answer, collection: kpi.kpis_segments.map{|s| [s.text, s.id]}, as: :radio_buttons, label: kpi.name, required: true

      - if resource.brands.any?
        fieldset
          legend.competitive Competitive awareness & usage

          p For each of the following brands, please let us know if you have purchased the product in the past 12 months, are aware of the product, or are unaware of the product
          ul.competitive
            li
              .titles
                span PURCHASED
                span AWARE
                span UNAWARE
            li
              - resource.brands.each do |brand|
                = f.simple_fields_for :surveys_answers, resource.answer_for(1, brand.id) do |qf|
                  .row-fluid.control-group id="question-1-brand-#{brand.id}"
                    label.radio-brand
                      = brand.name
                    .radio-group
                      = qf.hidden_field :brand_id
                      = qf.hidden_field :question_id
                      label.radio= qf.radio_button :answer, 'purchased', class: 'required'
                      label.radio= qf.radio_button :answer, 'aware', class: 'required'
                      label.radio= qf.radio_button :answer, 'unaware', class: 'required'


          p For each brand that you have used, approximately how much do you spend each month?

          ul
            - resource.brands.each do |brand|
              li
                = f.simple_fields_for :surveys_answers, resource.answer_for(2, brand.id) do |qf|
                  .row-fluid.control-group id="question-2-brand-#{brand.id}" data-observe="#question-1-brand-#{brand.id}" data-observe-value="purchased"
                    .hidden-label
                      label.radio= brand.name
                      = qf.hidden_field :brand_id
                      = qf.hidden_field :question_id

                    .hidden-field
                      .add-on $
                      = qf.text_field :answer, class: 'required'

        fieldset
          legend.conversion Conversion likehood

          p For each of the following brands, please let us know how likely you are to purchase the brand in the next 12 months? Please answer on a 1 to 5 scale where 1 = not at all likely and 5 = very likely.

          ul.conversion
            li
              .titles
                span
                  | VERY UNLIKELY
                  br
                  | 1
                span 2
                span 3
                span 4
                span
                  | VERY LIKELY
                  br
                  | 5
            - resource.brands.each do |brand|
              li
                = f.simple_fields_for :surveys_answers, resource.answer_for(3, brand.id) do |qf|
                  .row-fluid.control-group
                    label.radio-brand= brand.name
                    .radio-group
                      = qf.hidden_field :brand_id
                      = qf.hidden_field :question_id
                      label.radio= qf.radio_button :answer, '1', class: 'required'
                      label.radio= qf.radio_button :answer, '2', class: 'required'
                      label.radio= qf.radio_button :answer, '3', class: 'required'
                      label.radio= qf.radio_button :answer, '4', class: 'required'
                      label.radio= qf.radio_button :answer, '5', class: 'required'


          p How likely are you to recommend the brand to a friend?  Please answer on a 0 to 10 scale where 0 is not at all likely and 10 = extremely likely

          ul.recommend
            li
              .titles
                span
                  | VERY UNLIKELY
                  br
                  | 1
                span 2
                span 3
                span 4
                span 5
                span 6
                span 7
                span 8
                span 9
                span
                  | VERY LIKELY
                  br
                  | 10
            tbody
              - resource.brands.each do |brand|
                = f.simple_fields_for :surveys_answers, resource.answer_for(4, brand.id) do |qf|
                  .row-fluid.control-group
                      label.radio-brand= brand.name
                      .radio-group
                        = qf.hidden_field :brand_id
                        = qf.hidden_field :question_id
                        label.radio= qf.radio_button :answer, '1', class: 'required'
                        label.radio= qf.radio_button :answer, '2', class: 'required'
                        label.radio= qf.radio_button :answer, '3', class: 'required'
                        label.radio= qf.radio_button :answer, '4', class: 'required'
                        label.radio= qf.radio_button :answer, '5', class: 'required'
                        label.radio= qf.radio_button :answer, '6', class: 'required'
                        label.radio= qf.radio_button :answer, '7', class: 'required'
                        label.radio= qf.radio_button :answer, '8', class: 'required'
                        label.radio= qf.radio_button :answer, '9', class: 'required'
                        label.radio= qf.radio_button :answer, '10', class: 'required'

    .form-actions
      = f.button :submit, 'Save', id: 'submit-expense-btn', class: 'btn btn-primary', data: {disable_with: 'Please wait...'}
      = "&nbsp;".html_safe
      = f.button :button, 'Cancel', class: 'btn btn-cancel'

javascript:
  $('[data-observe]').each(function(index, row){
    var $row = $(row);
    $($row.data('observe')+' input[type=radio]').change(function(){
      if ($(this).val() != $row.data('observe-value')){
        $row.find('input[type=text][name*=answer]').val('')
        $row.hide().find('.required').removeClass('required')
      } else {
        $row.show().find('input[type=text]').addClass('required')
      }
    })
    if ($($row.data('observe')+' input[type=radio]:checked').val() != $row.data('observe-value')) {
      $row.hide().find('.required').removeClass('required');
      $row.find('input[type=text][name*=answer]').val('')
    } else {
      $row.show().find('input[type=text]').addClass('required');
    }
  });

app/views/surveys/_settings.slim
- @form_modal_class = 'modal-xlarge'

app/views/surveys/_survey.html.slim
div.resource-item id="survey_#{survey.id}"
  .resource-item-link
    .span4
      .survey-age
        - if age = survey.age
          = "#{age} year old"
      = "#{survey.ethnicity} #{survey.gender}"
    .span4.date
      = format_date(survey.created_at)
      br>/
      | Completed
    .span4.date
      = format_date(survey.updated_at)
      br>/
      | Modified
  div.resource-item-actions
    = button_to_edit survey, url: edit_event_survey_path(survey.event, survey) if can?(:edit, survey)
    = button_to_activate_or_deactivate(survey, activate_url: activate_event_survey_path(survey.event, survey), deactivate_url: deactivate_event_survey_path(survey.event, survey)) if can?(:deactivate, survey)

app/views/surveys/create.js.slim
- if resource.errors.any?
	- resource.surveys_answers.select{|a| !a.valid? }.each{|a| puts a.errors.inspect }
	= render 'form_dialog'
- else
	|
	  $('.bootbox.modal').modal('hide');
	  $('#event-surveys-list').html('#{j render(parent.surveys)}')