config/routes.rb
Brandscopic::Application.routes.draw do

  mount Nkss::Engine => '/styleguides' if Rails.env.development?
  apipie if ENV['WEB']

  # Redirect old urls to new ones
  get '/results/gva', to: redirect('/analysis/gva')
  get '/results/event_status', to: redirect('/analysis/event_status')
  get '/results/attendance', to: redirect('/analysis/attendance')

  concern :deactivatable do
    get :deactivate, on: :member
    get :activate, on: :member
  end

  concern :filterable do
    get :items, on: :collection, format: :html
  end

  concern :commentable do
    resources :comments, only: [:index, :create, :update, :destroy]
  end

  concern :api_attachable do
    get :form, on: :collection
  end

  concern :form_field_exportable do
    get :form, action: :export_fieldable, on: :member
    get :export_results, on: :member
  end

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create'
        delete 'sessions' => 'sessions#destroy'

        get '/companies' => 'users#companies'
        resources :users, only: [:index, :update, :show] do
          collection do
            match 'password/new_password', to: 'users#new_password', via: :post
            get :permissions
            get :notifications
          end
        end
        resources :activities, only: [:new, :show]

        resources :filters, only: [:show]

        resources :events, only: [:index, :show, :create, :update], concerns: [:commentable] do
          get :status_facets, on: :collection
          get :requiring_attention, on: :collection
          post :filter, to: 'events#index', on: :collection
          resources :photos, only: [:index, :create, :update], concerns: [:api_attachable]
          resources :documents, only: [:index, :create, :update], concerns: [:api_attachable]
          resources :event_expenses, only: [:index, :create, :destroy, :update], concerns: [:api_attachable]
          resources :tasks, only: [:index, :create]
          resources :surveys,  only: [:index, :create, :update, :show] do
            get :brands, on: :collection
          end
          resources :invites, only: [:index, :show, :create, :update]
          resources :activities, only: [:index, :create, :update], concerns: [:deactivatable, :api_attachable] do
            get :deactivate, on: :member
          end
          get :autocomplete,   on: :collection
          member do
            put :submit
            put :reject
            put :approve
            get :results
            get :members
            post :members, to: 'events#add_member'
            delete :members, to: 'events#delete_member'
            get :assignable_members
            get :contacts
            post :contacts, to: 'events#add_contact'
            delete :contacts, to: 'events#delete_contact'
            get :assignable_contacts
            get :details_counters
          end
        end

        resources :campaigns, only: [] do
          collection do
            get :all
            get :overall_stats
          end
          resources :activity_types, only: [:index]
          resources :brands, only: [:index]
          get :stats, on: :member
          get :events, on: :member
          get :expense_categories, on: :member
        end

        resources :activity_types, only: [:index] do
          member do
            get :campaigns
          end
        end

        resources :venues, only: [:index, :show, :create] do
          get :search, on: :collection
          get :types, on: :collection
          get :autocomplete, on: :collection
          resources :invites, only: [:index, :show, :create, :update]
          resources :activities, only: [:index, :create, :update] do
            get :deactivate, on: :member
          end
          member do
            get :analysis
            get :photos
            get :comments
          end
        end

        resources :areas, only: [:index] do
          get :cities, on: :member
        end

        resources :brands, only: [:index] do
          get :marques, on: :member
        end

        resources :countries, only: [:index] do
          get :states, on: :member
        end

        resources :contacts, only: [:index, :create, :update, :show]

        resources :tasks, only: [:update, :create, :show], concerns: [:commentable] do
          collection do
            get :mine, action: :index, defaults: { scope: 'user' }, constraints: { scope: 'user' }
            get :team, action: :index, defaults: { scope: 'teams' }, constraints: { scope: 'teams' }
          end
        end

        namespace :brand_ambassadors do
          resources :visits, only: [:index, :create, :update, :show] do
            get :types, on: :collection
            get :events, on: :member
          end
          resources :documents, only: [:create, :update, :destroy, :index]
        end
      end
    end
  end

  if ENV['WEB']
    require 'sidekiq/web'
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    authenticate :admin_user do
      mount Sidekiq::Web => '/_bgjobs' unless Rails.env.test?
    end
  end

  devise_for :users, controllers: { invitations: 'invitations', passwords: 'passwords' }

  devise_scope :user do
    put '/users/confirmation', to: 'confirmations#update'
    get '/users/invitation/resend', to: 'invitations#resend'
    get '/users/invitation/renew', to: 'invitations#renew'
    post '/users/invitation/resend', to: 'invitations#send_invite'
    get '/users/password/thanks', to: 'passwords#thanks', as: :passwords_thanks
  end

  put '/users/dismiss_alert', to: 'company_users#dismiss_alert'

  get 'select-company/:company_id', to: 'company_users#select_company', as: :select_company, constraints: { company_id: /[0-9]+/ }
  put 'login-as', to: 'company_users#select_custom_user', as: :select_custom_user

  resources :countries, only: [] do
    get :states, on: :collection
    get :cities, on: :member
  end

  get '/notifications.json', to: 'company_users#notifications', format: :json

  get 'exports/:download_id/status', to: 'company_users#export_status', as: :export_status, format: :json

  resources :goals, only: [:create, :update]

  resources :photos, only: [:show]

  # /filters/events /filters/campaigns etc
  resources :filters, only: [:show] do
    get :expand, on: :collection
  end

  # /autocomplete/events /autocomplete/campaigns etc
  resources :autocomplete, only: [:show]

  namespace :results do
    resources :event_data, only: [:index], concerns: [:filterable]
    resources :comments, only: [:index], concerns: [:filterable]
    resources :photos, only: [:index], concerns: [:filterable] do
      post 'downloads', to: 'photos#new_download', on: :collection, format: :js
      get 'downloads/:download_id', to: 'photos#download', on: :collection, as: :download, format: :js
      get 'downloads/:download_id/status', to: 'photos#download_status', on: :collection, as: :download_status, format: :json
    end
    resources :activities, only: [:index], concerns: [:filterable]
    resources :expenses, only: [:index], concerns: [:filterable]
    resources :surveys, only: [:index], concerns: [:filterable]

    # resources :attendance, only: [:index] do
    # end

    resources :reports, only: [:index, :new, :create, :edit, :update, :show],
                        concerns: [:deactivatable] do
      get :build, on: :member
      get :rows, on: :member
      get :filters, on: :member
      get :share, to: 'reports#share_form', on: :member
      post :preview, on: :member
    end

    resources :data_extracts, only: [:new, :create, :show, :edit, :update] do
      get :preview, on: :collection
      get :save, on: :collection
      get :available_fields, on: :collection
      get :items, on: :collection
      get :deactivate, on: :member
      get :activate, on: :member
    end

    # For The KPI report
    get :kpi_report, to: 'kpi_reports#index'

    post :kpi_report, to: 'kpi_reports#report'
    get :kpi_report_status, to: 'kpi_reports#status'

  end

  namespace :analysis do
    resources :trends, only: [] do
      collection do
        get :sources
        get :questions
        get :results
        get :items
        get :filters
        get :search
      end
      get 't/:term', on: :collection, action: :show
      get 't/:term/:action', on: :collection
    end

    get 'attendance/map', to: 'attendance#map', as: :attendance_map
    get 'attendance', to: 'attendance#index', as: :attendance

    get :gva, to: 'gva#index'
    post :gva, to: 'gva#report'
    get :report_groups, to: 'gva#report_groups'

    get :event_status, to: 'event_status#index'
    post :event_status, to: 'event_status#report'

    get :campaigns_report, to: 'campaigns_report#index'
    post :campaigns_report, to: 'campaigns_report#report'

    get :staff_report, to: 'staff_report#index'
    post :staff_report, to: 'staff_report#report'

    get :campaign_summary_report, to: 'campaign_summary_report#index'
    get :campaign_summary_report_show_all, to: 'campaign_summary_report#show_all'
    post :campaign_summary_report, to: 'campaign_summary_report#report'
    get :campaign_summary_report_export, to: 'campaign_summary_report#export_results'
    get :campaign_summary_report_items, to: 'campaign_summary_report#items'
    get :campaign_summary_report_result, to: 'campaign_summary_report#result'

    get '/', to: 'analysis#index'
  end

  scope '/research' do
    resources :venues, only: [:index, :show], concerns: [:filterable] do
      member do
        match 'areas/:area_id' => 'venues#delete_area', via: :delete, as: :delete_area
        match 'areas/select' => 'venues#select_areas', via: :get, as: :select_areas
        match 'areas/add' => 'venues#add_areas', via: :post, as: :add_area
        match 'areas' => 'venues#areas', via: :get, as: :areas
      end
      resources :events, only: [:new, :create]

app/models/data_extract/company_user.rb
# == Schema Information
#
# Table name: data_extracts
#
#  id               :integer          not null, primary key
#  type             :string(255)
#  company_id       :integer
#  active           :boolean          default("true")
#  sharing          :string(255)
#  name             :string(255)
#  description      :text
#  columns          :text
#  created_by_id    :integer
#  updated_by_id    :integer
#  created_at       :datetime
#  updated_at       :datetime
#  default_sort_by  :string(255)
#  default_sort_dir :string(255)
#  params           :text
#

class DataExtract::CompanyUser < DataExtract
  define_columns first_name: 'users.first_name',
                 last_name: 'users.last_name',
                 teams_name: 'array_to_string(ARRAY(SELECT teams.name FROM teams
                             LEFT JOIN memberships ON memberable_type=\'Team\' AND memberable_id=teams.id
                             WHERE company_users.id=memberships.company_user_id  ),\', \') AS teams_name',
                 email: 'users.email',
                 phone_number: 'users.phone_number',
                 role_name: 'roles.name',
                 address1: 'users.street_address',
                 address2: 'users.unit_number',
                 country: 'users.country',
                 city: 'users.city',
                 state: 'users.state',
                 zip_code: 'users.zip_code',
                 time_zone: 'users.time_zone',
                 created_at: proc { "to_char(users.created_at, 'MM/DD/YYYY')" },
                 created_by: '(SELECT trim(us.first_name || \' \' || us.last_name) FROM users as us WHERE users.created_by_id=us.id)',
                 modified_at: proc { "to_char(users.updated_at, 'MM/DD/YYYY')" },
                 modified_by: '(SELECT trim(us.first_name || \' \' || us.last_name) FROM users as us WHERE users.updated_by_id=us.id)',
                 active_state: 'CASE WHEN company_users.active=\'t\' THEN \'Active\' ELSE \'Inactive\' END'

  def add_joins_to_scope(s)
    s = s.joins('LEFT JOIN users ON users.id=company_users.user_id')
    if columns.include?('role_name')
      s = s.joins('LEFT JOIN roles ON roles.id=company_users.role_id')
    end
    s
  end

  def add_filter_conditions_to_scope(s)
    return s if filters.nil? || filters.empty?
    s = s.where(role_id: filters['role']) if filters['role'].present?
    s = s.joins('LEFT JOIN memberships AS member ON member.memberable_type=\'Team\'')
          .where("member.memberable_id IN (#{filters['team'].join(', ')}) AND company_users.id=member.company_user_id") if filters['team'].present?
    s = s.joins('LEFT JOIN memberships AS member_campaign ON member_campaign.memberable_type=\'Campaign\'')
          .where("member_campaign.memberable_id IN (#{filters['campaign'].join(', ')}) AND company_users.id=member_campaign.company_user_id") if filters['campaign'].present?
    s = add_filter_status(s)
    s
  end

  def add_filter_status(s)
    filters[:status].each do |status|
      s = s.where(active: filters['status'].map { |f| f.downcase == 'active' ? true : false }) if status.downcase == 'active' || status.downcase == 'inactive'
      s = s.where('users.invited_by_id is not null') if status.downcase == 'invited'
    end if filters[:status].present?
    s
  end

  def total_results
    CompanyUser.connection.select_value("SELECT COUNT(*) FROM (#{base_scope.select(*selected_columns_to_sql).to_sql}) sq").to_i
  end

  def sort_by_column(col)
    case col
    when 'created_at'
      'users.created_at'
    else
      super
    end
  end
end

app/views/company_users/_areas_and_places.html.slim
h5.module-title PLACES
- if resource.areas.any? || resource.places.any?
  #company_user-areas-list
   = render partial: 'company_users/area', collection: resource.areas.order('areas.name ASC'), locals: { resource: resource }

  #company_user-places-list
    = render partial: 'company_users/places', locals: { resource: resource }, formats: [:html]

  .row-fluid.plus
    = button_to_add "Add Place", select_form_areas_path(company_user_id: resource.id) if can?(:edit, resource)

- else
  = blank_state_module('company_users.places') do
    = button_to 'Add Place', select_form_areas_path(company_user_id: resource), remote: true, method: :get, class: 'btn btn-primary'  if can?(:edit, resource)

app/views/company_users/_campaign.html.slim
.span4.user-campaign.hover-item id="company_user-campaign-#{campaign.id}"
  .pull-left
    = campaign.name
  .pull-right
    = link_to '', remove_campaign_company_user_path(resource, {campaign_id: campaign.id}.merge( parent.nil?  ? {}  : {parent_type: parent.class.name, parent_id: parent.id})), method: :delete, remote: true, class: 'icon-remove-circle', title: 'Remove Campaign'

app/views/company_users/_campaigns.html.slim
/ / CAMPAIGNS ASSIGNED TO THE USER DIRECTLY
/ .campaigns-group
/   .campaigns-group-body
/     .row-fluid.campaigns-list id="campaigns-company_user-#{resource.id}"
/         = render partial: 'company_users/campaign', collection: resource.campaigns, locals: {parent: nil}


/ CAMPAIGNS GROUPED BY BRAND
- brands_campaigns_list.each do |parent, info|
  = render partial: 'campaings_bucket', locals: {parent: parent, enabled: info[:enabled], campaigns: info[:campaigns]}


- if can?(:edit, resource)
  javascript:
    $(document).delegate('.toggle-off-btn', 'click', function(e){
      $(this).parent().addClass('active').removeClass('deactive');
      $.post('#{enable_campaigns_company_user_path(resource)}', {parent_id: $(this).data('parent-id'), parent_type: $(this).data('parent-type')});
      return false;
    });
    $(document).delegate('.toggle-on-btn', 'click', function(e){
      $(this).parent().addClass('inactive').removeClass('active');
      $.post('#{disable_campaigns_company_user_path(resource)}', {parent_id: $(this).data('parent-id'), parent_type: $(this).data('parent-type')});
      return false;
    });


/ Markup for new design
- if false
  .details_box.user-view
    .user-data
      h3 CAMPAIGNS

      .items-container
        .box.special-icon.brand-icon
          b example one - brand icon

        .box.special-icon.brand-icon
          b Absolut Bloody Incremental FY14

        .box.special-icon.brand-icon
          b Absolut Texas Incremental Mini

        .box.special-icon.brand-icon
          b Jameson Black Barrel Summer MBN FY14

        .box.special-icon.brand-icon
          b Jameson FY14

        .box.special-icon.brand-icon
          b example one - brand icon

      .items-container
        .box.special-icon.campaign-icon
          b example one - campaign icon

        .box.special-icon.campaign-icon
          b example one - campaign icon

        .box.special-icon.campaign-icon
          b Jameson MBN FY14

        .box.special-icon.campaign-icon
          b example one - campaign icon

        .box.special-icon.campaign-icon
          b Kahla BA Incremental

        .box.special-icon.campaign-icon
          b example one - campaign icon

      = link_to "Add campaigns"

app/views/company_users/_campaings_bucket.html.slim
.campaigns-group
  .row-fluid.campaigns-group-header
    .pull-left
      div class="switch-toggle #{enabled ? 'active' : 'inactive'}" id="campaigns-toggle-#{parent.class.name}-#{parent.id}"
        a.btn.btn-small.toggle-on-btn href="#" id="toggle-bucket-off" title="Toggle OFF" data-parent-id="#{parent.id}" data-parent-type="#{parent.class.name}"
          span
          .on ALL
        a.btn.btn-small.toggle-off-btn href="#" id="toggle-bucket-on" title="Toggle ON" data-parent-id="#{parent.id}" data-parent-type="#{parent.class.name}"
          span
          .off
    .pull-left
      h4 = parent.name



  .campaigns-group-body
    .row-fluid.campaigns-list id="campaigns-#{parent.class.name}-#{parent.id}"
        = render partial: 'company_users/campaign', collection: campaigns, locals: {parent: parent}

    .row-fluid
      = link_to '', select_campaigns_company_user_path(resource, parent_type: parent.class.name, parent_id: parent.id), remote: true, class: 'icon-plus-sign', id: "btn-add-campaign-#{parent.class.name}-#{parent.id}", style: "display: #{enabled ? 'none' : 'inline'};"

app/views/company_users/_form.html.slim
- remote ||= false
- is_admin = can?(:super_update, resource)
= simple_form_for(resource, remote: remote || false) do |f|
  = f.error_notification

  .form-inputs
    = f.simple_fields_for :user do |uf|
      .row-fluid.users
        .span6
          = uf.input :first_name, input_html: {class: 'input-large'}, :autofocus => true
        .span6
          = uf.input :last_name, input_html: {class: 'input-large'}

      - if is_admin
        .row-fluid.users
            = f.association :teams, collection: company_teams.active.all, input_html: {class: 'input-xxlarge chosen-enabled', "data-placeholder" => 'Select Teams'}
      .row-fluid.users
        - if resource.unconfirmed_email.present? && resource.unconfirmed_email != resource.email
          .email-confirmation-message
            p== "Check your (<b>#{resource.unconfirmed_email}</b>) to confirm your new address. Until you confirm, you will continue to use your current email address."
            = link_to 'Resend confirmation', resend_email_confirmation_company_user_path(resource), data: { disable_with: 'Sending' }, remote: true
            = link_to 'Cancel this change', cancel_email_change_company_user_path(resource), data: { disable_with: 'Sending' }, remote: true

        = uf.input :email, input_html: {class: 'input-xxlarge'}
      .row-fluid.users
        = uf.input :phone_number, input_html: {class: 'input-xxlarge'}, required: !is_admin

      - if is_admin && resource.id != current_company_user.id
        .row-fluid.users-teams-roles
          = f.input :role_id, as: :select, collection: current_company.roles.active.not_admin, input_html: {class: 'input-large chosen-enabled'}
      - if resource.id == current_company_user.id || is_admin
        .row-fluid.users
            = uf.input :password, input_html: {class: 'input-xxlarge', minlength: 8, maxlength: 128}, hint: 'Password must contain at least 8 characters, at least 1 number, at least 1 lowercase character (a-z) and at least 1 uppercase character (A-Z)'
        .row-fluid.users
            = uf.input :password_confirmation, input_html: {class: 'input-xxlarge'}
        .row-fluid.users
          = uf.input :street_address, label: 'Address', input_html: {class: 'input-xxlarge'}, required: !is_admin
        .row-fluid.users
          = uf.input :unit_number, label: false, input_html: {class: 'input-xxlarge'}, required: false
        .row-fluid.users
          .span6
            = uf.input :country, input_html: {class: 'input-large chosen-enabled'}, priority: ['US'], iso_codes: true, required: !is_admin
          .span6
            = uf.input :city, input_html: {class: 'input-large'}, required: !is_admin
        .row-fluid.users
          .span6
            = uf.input :state, collection: (resource.country.present? ? Country.new(resource.country).states.map{|k, info| [info['name'],k]} : []), input_html: {class: 'input-large chosen-enabled'}, required: !is_admin
          .span6
            = uf.input :zip_code, input_html: {class: 'input-large'}, required: !is_admin
        .row-fluid.users-teams-roles
          = uf.input :time_zone, input_html: {class: 'input-large chosen-enabled'}, required: !is_admin

  .form-actions
    = f.button :submit, 'Save', class: 'btn btn-primary', data: {disable_with: 'Please wait...'}
    = "&nbsp;".html_safe
    = f.button :button, 'Cancel', class: 'btn btn-cancel'

- unless resource.time_zone.present?
  javascript:
    $('#company_user_user_attributes_time_zone').set_timezone({'mappings':#{ActiveSupport::TimeZone::MAPPING.invert.to_json.html_safe}});

coffee:
  $('#company_user_user_attributes_country').change () ->
    $.get '/countries/states.json', {country: $(this).val()}, (response) ->
      states = $('#company_user_user_attributes_state')
      val = states.val()
      states.html('<option></option>')
      if response.states
        for state in response.states
          option = $('<option>').val(state.id).html(state.name)
          if val is state.id
            option.attr('selected', 'selected')
          states.append(option)
      states.trigger('liszt:updated')

app/views/company_users/_help_tutorial.html.slim
- content_for :help_title do
  - if params[:id].present?
    | View and edit specific information about a user related to campaigns and goals
  - else
    | Invite and manage users from this area (dependent on your permissions). Invited users will get email welcome messages and be able to enter in their own personal information
.help-overlay-definitions
  //For index
  div data-target="#application-content" data-intro="Click anywhere or press Esc to close" data-position="top" data-element-class="chardinjs-keep-back" data-tooltip-style="top: -26px;"
  div data-target="#users-list li:nth-child(1) .user_name" data-intro="A users's name and their system access level" data-position="bottom" data-tooltip-style="bottom: -70px; left: -35px; width: 185px; padding-top: 0;"
  div data-target="#users-list li:nth-child(1) .user_city" data-intro="A users's physical address" data-position="bottom" data-tooltip-style="bottom: -50px; left: -40px; width: 185px; padding-top: 0;"
  div data-target="#users-list li:nth-child(1) .user_mail" data-intro="Contact email address" data-tooltip-style="bottom: -50px; left: -35px; width: 185px; padding-top: 0;"
  div data-target="#users-list li:nth-child(1) .user_date" data-intro="The date of the last activity such as a user login" data-tooltip-style="bottom: -70px; left: -40px; width: 185px; padding-top: 0;"
    div data-target="#users-list li:nth-child(2) .tools" data-intro="Users can be deactivated or edited (e.g., access level, password change, time zone settings)" data-position="bottom" data-tooltip-style="width: 197px; left: -84px; bottom: -116px; padding-top: 0px;"

  div data-target="#search-box-filter" data-intro="Search for specific users by role, team and campaign" data-position="top" data-tooltip-style="top: -39px; left: -14px;"

  div data-target=".form-facet-filters" data-intro="Filter users by selecting multiple criteria" data-position="left" data-helper-class="chardinjs-dashed" data-element-class="chardinjs-keep-back" data-tooltip-style="top: 30px; left: -127px;"

  div data-target="#save-filters-btn" data-intro="Save filtering combinations you use regularly" data-position="left" data-tooltip-style="top: -18px; left: -127px;"

  div data-target=".btn-download" data-intro="Export users to Excel or PDF" data-position="left" data-tooltip-style="top: -4px; left: -127px;"



  //For show
  div data-target=".padding-top-close-bar h2" data-intro="View the critical information about a user including their name, access level and contact information" data-position="right" data-element-class="chardinjs-keep-back" data-tooltip-style="top: 92px; left: 262px; width: 420px;"
  div data-target=".links-data" data-intro="Edit or deactivate a user by clicking here" data-position="right"  data-tooltip-style="top: -7px; left: 85px;"
  div data-target="#user-places" data-intro="Add or remove users from Places or Areas (a defined group of places)" data-position="right" data-element-class="chardinjs-keep-back" data-tooltip-style="left: 91px; top: 117px; width: 196px;"
  div data-target=".switch-toggle:nth-child(1)" data-intro="Add or remove users from all campaigns in a brand by toggling this on/off" data-position="right" data-tooltip-style="top: -26px; right: -110px;"
  div data-target=".campaigns-group-body a.icon-plus-sign" data-intro="Click to add a user to a specific campaign" data-position="right" data-tooltip-style="top: -15px; right: -112px; padding-top: 0px;"
  //div data-target="a.icon-remove-circle" data-intro="Click to remove a user from an individual campaign" data-position="bottom" data-tooltip-style="top: 146px; left: -65px; padding-top: 0px;"
  div data-target=".btn-add-goal" data-intro="Add user-specific goals and start/end dates for those goals" data-position="right" data-tooltip-style="top: -23px; right: -123px;"
  div data-target="#resource-goals-list li:nth-child(1) a.edit" data-intro="Edit goals and start/end dates" data-tooltip-style="bottom: -46px; left: -50px; width: 130px; padding-top: 0;"

app/views/company_users/_place.html.slim
.span3.place.clearfix.hover-item id="company_user-place-#{place.id}"
  .pull-left
    .place-name
      = place.name
    .place-address
      = place.formatted_address
  .pull-right
    = link_to '',  company_user_place_path(resource, place), method: :delete, remote: true, class: 'icon-remove-circle', title: 'Remove Place'

app/views/company_users/_places.html.slim
= render partial: 'company_users/place', collection: resource.places, locals: { resource: resource }

app/views/company_users/_select_campaigns.html.slim
input#campaign-search-box.search-box.select-list-seach-box type="text" name="q" data-list="#user-campaigns-list"
#user-campaigns-list.resource-list.select-list
  - @campaigns.each do |campaign|
    .resource-item id="campaign-#{campaign.id}"
      .resource-item-link
        .text-large= campaign.name
        = campaign.description
      .resource-item-actions
        = link_to '', add_campaign_company_user_path(resource, parent_id: params[:parent_id], parent_type: params[:parent_type], campaign_id: campaign.id), remote: true, method: :post, data: {disable_with: '...'}, class: 'icon-plus-sign', title: 'Add Campaign'

app/views/company_users/_send_code.html.slim
= simple_form_for(resource, url: verify_phone_company_user_path(resource), method: :post, remote: true) do |f|
  p
    | We will send you a message to
    b>  #{resource.phone_number}
    |  with a code.

  .form-actions
    = f.button :submit, 'Send', class: 'btn btn-primary', data: {disable_with: 'Please wait...'}
    = "&nbsp;".html_safe
    = f.button :button, 'Cancel', class: 'btn btn-cancel'

app/views/company_users/_settings.slim
- @form_modal_class = 'modal-large'

app/views/company_users/enable_campaigns.js.slim
|
  $('#campaigns-#{params[:parent_type]}-#{params[:parent_id]}').html('#{j render(partial: 'company_users/campaign', collection: @campaigns, locals: {parent: @parent})}')
  $('#btn-add-campaign-#{params[:parent_type]}-#{params[:parent_id]}').hide();

app/views/company_users/remove_campaign.js.slim
|
  $('#campaigns-#{params[:parent_type]}-#{params[:parent_id]} #company_user-campaign-#{params[:campaign_id]}').remove();
  $('#campaigns-toggle-#{params[:parent_type]}-#{params[:parent_id]}').removeClass('active').addClass('inactive');
  $('#btn-add-campaign-#{params[:parent_type]}-#{params[:parent_id]}').show();

app/views/company_users/time_zone_change.js.slim
|
  var tzmodal = bootbox.confirm($('<div>#{escape_javascript(render(partial: 'time_zone_change'))}</div>'), function(result){
    if (result){
      $.ajax({
          url: '#{time_zone_update_company_users_path(format: :js)}',
          type: 'PUT',
          data: {time_zone: '#{escape_javascript(params[:time_zone].html_safe)}'}
      });
    }
  });
		